INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(SNAPPY_INCLUDE_DIR
  NAMES snappy.h 
)
FIND_LIBRARY(SNAPPY_LIBRARY
  NAMES snappy
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Snappy "Could NOT find snappy." SNAPPY_INCLUDE_DIR SNAPPY_LIBRARY)

